on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust_channel:
          - stable
          - nightly
    steps:
      - run: rustup --version
      - uses: actions/checkout@v4
      - run: rustup toolchain add --profile=minimal ${{ matrix.rust_channel }}
      - run: cargo clippy --all-features --all-targets -- -D warnings
