name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust_channel:
          - stable
          - nightly
    steps:
      - run: rustup --version
        name: Check rustup
      - uses: actions/checkout@v4
      - run: rustup toolchain add --profile=minimal ${{ matrix.rust_channel }}
        name: Install toolchain
      - run: cargo clippy --all-features --all-targets -- -D warnings
        name: Clippy check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
